services:
  odoo:
    # image: odoo:17.0
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: odoo
    volumes:
      - ..:/workspace
      - ./config:/etc/odoo:rw
      - odoo-data:/var/lib/odoo
    ports:
      - "8069:8069"
    environment:
      - HOST=postgres
      - USER=odoo
      - PASSWORD=odoo
      - DATABASE=test
      - STAGE=dev
      - LANGUAGE=fr_FR
      - COUNTRY=FR
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data:
  odoo-data:
